/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as EventsEventIdInvitationsRouteImport } from './routes/events/$eventId/invitations'
import { Route as EventsEventIdScheduleRouteImport } from './routes/events/$eventId/schedule'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdInvitationsRoute =
  EventsEventIdInvitationsRouteImport.update({
    id: '/events/$eventId/invitations',
    path: '/events/$eventId/invitations',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventIdScheduleRoute = EventsEventIdScheduleRouteImport.update({
  id: '/events/$eventId/schedule',
  path: '/events/$eventId/schedule',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/events/$eventId/invitations': typeof EventsEventIdInvitationsRoute
  '/events/$eventId/schedule': typeof EventsEventIdScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/events/$eventId/invitations': typeof EventsEventIdInvitationsRoute
  '/events/$eventId/schedule': typeof EventsEventIdScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/events/$eventId/invitations': typeof EventsEventIdInvitationsRoute
  '/events/$eventId/schedule': typeof EventsEventIdScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/events/$eventId/invitations'
    | '/events/$eventId/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/events/$eventId/invitations'
    | '/events/$eventId/schedule'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/events/$eventId/invitations'
    | '/events/$eventId/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  EventsEventIdInvitationsRoute: typeof EventsEventIdInvitationsRoute
  EventsEventIdScheduleRoute: typeof EventsEventIdScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/invitations': {
      id: '/events/$eventId/invitations'
      path: '/events/$eventId/invitations'
      fullPath: '/events/$eventId/invitations'
      preLoaderRoute: typeof EventsEventIdInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/schedule': {
      id: '/events/$eventId/schedule'
      path: '/events/$eventId/schedule'
      fullPath: '/events/$eventId/schedule'
      preLoaderRoute: typeof EventsEventIdScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  EventsEventIdInvitationsRoute: EventsEventIdInvitationsRoute,
  EventsEventIdScheduleRoute: EventsEventIdScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
