/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsEventIdScheduleRouteImport } from './routes/events/$eventId/schedule'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdScheduleRoute = EventsEventIdScheduleRouteImport.update({
  id: '/events/$eventId/schedule',
  path: '/events/$eventId/schedule',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$eventId/schedule': typeof EventsEventIdScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$eventId/schedule': typeof EventsEventIdScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$eventId/schedule': typeof EventsEventIdScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/events/$eventId/schedule'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events/$eventId/schedule'
  id: '__root__' | '/' | '/events/$eventId/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsEventIdScheduleRoute: typeof EventsEventIdScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/schedule': {
      id: '/events/$eventId/schedule'
      path: '/events/$eventId/schedule'
      fullPath: '/events/$eventId/schedule'
      preLoaderRoute: typeof EventsEventIdScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsEventIdScheduleRoute: EventsEventIdScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
